### ISSUE TITLE
Change of layoutManager breaks instantSearch infiniteScroll

### ISSUE THREAD

**Issue by andreasmakeable** [algolia/instantsearch-android#110]
**Do you want to request a *feature* or report a *bug*?**

**Bug: What is the current behavior?**
When changing the layoutManager, all paging (infiniteScroll) stops working

**Bug: What is the expected behavior?**
I expect the Hits view to work regardles of the chosen layoutManager, like a normal RecyclerView does.

**Bug: What is the proposed solution?**
in Hits.java, remove the local property "layoutManager" as it is already defined in the RecyclerView super class. The use of the property is to calculate if loading more items is needed, and the superClass layoutManager can be used for that. Having a private layoutManager makes the super property of the same name useless, as the private local copy is used for paging. 

**What is the version you are using? Always try to use the latest one before opening a bug issue.**
implementation 'com.algolia:instantsearch-androidx:1.14.2'

**Comment by PLNech** [comment]
Hi @andreasmakeable, thanks for reporting this bug! I'll investigate how we can leverage the existing `layoutManager` and will update you here.

**Comment by andreasmakeable** [comment]
I have forked your project, and fixed the issue, and am now using the corrected version myself. So you can look there for inspiration in the "Hits.java" file. Very simple changes.

**Comment by PLNech** [comment]
Hi @andreasmakeable, thanks for this hint! However your repo seems to be private:
![image](https://user-images.githubusercontent.com/1821404/51250476-cad11680-1996-11e9-95e4-ef6c0e4a6696.png)
Would you mind sharing your changes as a diff here, or giving me read access? :pray:

**Comment by andreasmakeable** [comment]
> https://github.com/makeabledk/instantsearch-android

Just look there :)
