### ISSUE TITLE
Add xml option to use snippeted result instead of normal or highlighted

### ISSUE THREAD

**Issue by Benjoyo** [algolia/instantsearch-android#111]
There is an option algolia:highlighted to display highlighted results. There should be the same option to display only the snippeted result instead of the full one.
Using the databinding is pointless if it limits features too much so that I need to make a custom adapter anyway.

**Comment by PLNech** [comment]
Hi @Benjoyo, thanks for your feature request!

You're right, we should expose a `snippeted` attribute like we do for `highlighted`. I added this to our backlog and will update you here once released. 

As for using databinding, I agree that it should not limit what you can do with Algolia. We always try to balance _keeping InstantSearch Android easy to get started with_ versus _offering every Algolia feature_; but we don't always get it right from the first go. 

Keep sending us such feedback, this is key to us improving how we serve your needs :)

**Comment by PLNech** [comment]
Reopening until released.

**Comment by PLNech** [comment]
@benjoyo, starting with `v1.15.0` you can use `algolia:snippeted` like `algolia:highlighted`.
