### ISSUE TITLE
Images push down lists

### ISSUE THREAD

**Issue by PLNech** [algolia/instantsearch-android#12]
See in widgets, just before [SearchBox](https://community.algolia.com/instantsearch-android/getting-started.html#search-your-data-the-searchbox):

![image](https://cloud.githubusercontent.com/assets/1821404/24011273/9f854bcc-0a7a-11e7-99e2-2b70c9c126a2.png)

**Comment by LukyVj** [comment]
nice catch

**Comment by PLNech** [comment]
Now I right aligned again most screenshots, the issue persists:

![image](https://cloud.githubusercontent.com/assets/1821404/24367630/a1574d46-131d-11e7-8b42-e05e58c7fc76.png)

**Comment by PLNech** [comment]
This issue has been fixed in the last updates.
