### ISSUE TITLE
Integrate Javadoc

### ISSUE THREAD

**Issue by PLNech** [algolia/instantsearch-android#13]
Currently the API Reference looks like this:

![image](https://cloud.githubusercontent.com/assets/1821404/24011383/ee0b3f4a-0a7a-11e7-9a45-3fb3e0c19be0.png)

I don't think it is worth restyling the javadoc, however do you think we can have the same header as on the other pages, to improve consistency?

**Comment by LukyVj** [comment]
I think we could! But I'm not sure how, can we sync tomorow about it ?

**Comment by LukyVj** [comment]
Any idea how I could implement the header there ? @JonasBa 
A require? how would you do to import it on an html file?

**Comment by LukyVj** [comment]
I let this one open, I really have no idea on how to inject the header there.

**Comment by PLNech** [comment]
@JonasBa @LukyVj do you think we could make a page with the header and an iframe displaying `/javadoc`? This would be already better than raw javadoc, as users would be able to navigate back and would see somewhat consistent style :)

**Comment by PLNech** [comment]
Closed as stale/obsolete.
