### ISSUE TITLE
'aloglia:attribute' for ImageView sets image from another url if the attribute doesn't have a url

### ISSUE THREAD

**Issue by mustafabhatkar** [algolia/instantsearch-android#138]
I am using Hits widget to display the list of searched users. each item in the Hits has an ImageView and a TextView. Sometimes an item may not have an image url (algolia:attribute='@{"dp_url"}' may return null). In such case I want it to show an image from the 'android:source' attribute. 

This works well when I open the SearchActivity (where the Hits widget display the search result) for an empty query, It shows the image from the 'android:source' attribute for an item having no url. but when I start performing search. every item has some image. i.e. it no longer sets the image from the 'android:source' attribute.

Here is the screenshot
**When I open the search activity**
![screenshot_1548243564](https://user-images.githubusercontent.com/22981003/51604220-1d2fab80-1f32-11e9-8294-6306f1c0cf23.png)

**When I start searching**
![screenshot_1548243630](https://user-images.githubusercontent.com/22981003/51605182-4ea97680-1f34-11e9-8af7-98d27d95ff98.png)
**As you can see the same item which didn't have an image now has it**

**Is there a way by which I can fix this?**

**Comment by mustafabhatkar** [comment]
**Fixed it** by using a custom view which implements AlgoliaHitView. In the onUpdateView method by using Glide I am setting the appropriate image.

**Comment by PLNech** [comment]
Hi @mustafabhatkar, thanks for reporting this issue and sharing your solution!

I'm unsure why the `dp_url` image appeared when doing a search with `dav`, while the source was used in the empty query case. I'll investigate this, there might be a bug to fix here.

Regardless, you used the right approach: when you want to conditionally use one or another field of your records for display, the best approach is to implement an `AlgoliaHitView`. Hopefully this will help other users facing the same situation :slightly_smiling_face:

**Comment by PLNech** [comment]
Hello @mustafabhatkar, I'm back after trying to replicate this `dp_url` issue.

- I created a test index with a dataset with an attribute `dp_url` that either maps to an URL, to a `null`, or is absent (see following screenshot)
- I created a branch on [_instantsearch-android-mvp_](https://github.com/algolia/instantsearch-android-mvp), replicating your setup with a `Hits` widget using an `itemLayout` which has a `TextView` for `algolia:attribute='@{"name"}'` and an `ImageView` for `algolia:attribute='@{"dp_url"}'`
- I compared the results I see on a blank page (empty search) and after a search.

![Index data](https://user-images.githubusercontent.com/1821404/52798395-22d36980-3078-11e9-8b30-1d45adc63943.png)
![Screenshot on empty query](https://user-images.githubusercontent.com/1821404/52798431-3252b280-3078-11e9-8428-eb71dcb6c3ff.png)
![Screenshot with a query](https://user-images.githubusercontent.com/1821404/52798459-44345580-3078-11e9-8b7d-56ad41d43f8f.png)

----

It seems I'm unable to hit the issue you reported: regardless of the query I type, I see the placeholder for hits that lack a `dp_url` and the right image for each other.

- Could you [check that branch](https://github.com/algolia/instantsearch-android-mvp/tree/issue138) and let me know if this seems to replicate your setup? Maybe I missed something specific to your app.
- If nothing stands out, can you share a snapshot of your code (or a sample project) demonstrating that issue? It would be helpful to investigate further :slightly_smiling_face:
