### ISSUE TITLE
Clicking on community brings to InstantSearch Android and vice versa

### ISSUE THREAD

**Issue by PLNech** [algolia/instantsearch-android#14]
![image](https://cloud.githubusercontent.com/assets/1821404/24011516/4e12d042-0a7b-11e7-958d-5eebba3228cf.png)

- Click on community -> redirects to InstantSearch Android's landing page
- Click on InstantSearch Android -> redirects to community homepage

Shouldn't it be the opposite ? 🙂

**Comment by LukyVj** [comment]
hahahaha yes 
on it

**Comment by PLNech** [comment]
@JonasBa, @LukyVj tells me that this comes from your component: WDYT of this issue?

**Comment by LukyVj** [comment]
I think it can be modified in the `communityHeader.json` file, but for the " click on community to go on community" I think it's a matter of updating the component

**Comment by JonasBa** [comment]
@PLNech you can update that with the json file. Let me do, which branch is this on?

**Comment by PLNech** [comment]
@JonasBa in `master` (as should be everything: this is the main branch and every other one is a feature branch, we deploy on gh-pages what is in master's `docs` folder) :)
