### ISSUE TITLE
Hits component is flickering while typing search query

### ISSUE THREAD

**Issue by dbacinski** [algolia/instantsearch-android#146]
**Describe the bug 🐛**

Hits component is flickering/jumping when typing search query. It is even visible in your official example:
https://raw.githubusercontent.com/algolia/instantsearch-android/master/docgen/assets/img/ecommerce.gif

<com.algolia.instantsearch.ui.views.Hits
    android:id="@+id/hits_content_results"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    algolia:itemLayout="@layout/card_search"
    algolia:variant="hits" />

    algoliaSdk = '3.26.1'
    algoliaInstantSearch = '1.14.2'

**Expected behavior**
List items should not change position (especially few pixels up and down!) when the content of the screen stays the same

**Comment by q-litzler** [comment]
Hello,

Thank you for the feedback, you are right ! We will look into it and keep you posted.

**Comment by Aallam** [comment]
This issue does not seem to be present in the v2 of the library. The v1 will be deprecated.
