### ISSUE TITLE
Adding Instant Search Dependency Affects Theme

### ISSUE THREAD

**Issue by alisonthemonster** [algolia/instantsearch-android#147]
**Describe the bug 🐛**
When I add the dependency for instant search:
`    implementation 'com.algolia:instantsearch-androidx:1.15.2'` 
Then my theme is some how affected. Here are the screenshots before adding the dependency and after (no other code was changed):

Before:
![device-2019-02-09-155043](https://user-images.githubusercontent.com/10744793/52527791-2be0c700-2c83-11e9-8925-e67d2a776be4.png)

After:
![device-2019-02-09-155350](https://user-images.githubusercontent.com/10744793/52527800-592d7500-2c83-11e9-918f-69576501ce19.png)

Any idea why?

Here's my styles.xml file:
```
<resources>
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:textColor">#000000</item>
        <item name="android:windowBackground">@color/colorBackground</item>
    </style>

    <style name="SeekBarWithoutSteps" parent="Base.Widget.AppCompat.SeekBar.Discrete">
        <item name="tickMark">@null</item>
    </style>
</resources>
```

**Additional context**
I'm using the Material Components theme and working in kotlin.

**Comment by q-litzler** [comment]
Hello,

The following dependencies in instantsearch androidX is declared:

```
"com.google.android.material:material:1.1.0-alpha01",
```

This might affect your theme, and change the way certain component looks. Did you theme your application with this dependency in mind ? 

You can learn more about Material Design over [here](https://github.com/material-components/material-components-android).

Let us know if this helps, and reopen this issue if you still encounter difficulties.
