### ISSUE TITLE
Can't add params to Hits widget searcher

### ISSUE THREAD

**Issue by Geoffrey63** [algolia/instantsearch-android#149]
Hi, 
I'm using a `Hits` widget and I need to add params to the searcher used by this one.

I need to add the `disctinct` and the `facetingAfterDistinct` to the searcher.
The docs (https://www.algolia.com/doc/api-reference/api-parameters/distinct/) indicates that I need to pass params through the `index` :
```java 
index.setSettings(   
    new JSONObject()
        .put("distinct", 0) 
);
```
but the `searcher.getIndex()` method is deprecated.

Here is my equivalent iOS code (I have multiple searchers) : 
```swift
InstantSearch.shared.register(searchController: searchController)
var searchersIds: [SearcherId] = []
for (id, searcher) in InstantSearch.shared.searchers {
    searcher.params.clear()
    searcher.params.distinct = 1
    searcher.params.facetingAfterDistinct = true
    searchersIds.append(id)
}
```

Is there another way to set params to the searcher on Android ? 

Thanks for your reply.

**Comment by q-litzler** [comment]
Hello,

Sorry for the long delay. You can achieve what you want by using the Searcher `getQuery()` method. 
Once you have a reference to that query, you can modify it by passing parameters such as `distinct` and `facetingAfterDistinct`.

Let me know if this helps, closing this for now.
