### ISSUE TITLE
Widgets | SearchBox anchor does not work

### ISSUE THREAD

**Issue by PLNech** [algolia/instantsearch-android#15]
The link to SearchBox on the left bar seems broken:
![link](https://cloud.githubusercontent.com/assets/1821404/24203707/c285865a-0f16-11e7-8670-8a0568e7865d.gif)

Weirdly the id is `searchbox` and it seems the link is valid, but either clicking on it or manually typing the anchor in the url does not work. If we reopen the url and press enter, the page loads on the SearchBox, but that's only after a page reload. @LukyVj any idea what could cause this?

**Comment by Haroenv** [comment]
seems like the font is also broken from that gif

**Comment by Haroenv** [comment]
https://github.com/algolia/instantsearch-android/blob/master/docs/stylesheets/index.css#L3279 should be Montserrat too, or Open Sans should be loaded

**Comment by LukyVj** [comment]
Yeah it's related to https://github.com/algolia/algolia-components/issues/13

**Comment by LukyVj** [comment]
And I decided, until jonas or I update the component, to call the searchbox section `search-box`

**Comment by LukyVj** [comment]
@Haroenv I don't get the two lines you pasted ? What are they ?

**Comment by Haroenv** [comment]
They are why the font doesn't work
