### ISSUE TITLE
Data binding error

### ISSUE THREAD

**Issue by samtipton** [algolia/instantsearch-android#155]
**Describe the bug 🐛**
`e: [kapt] An exception occurred: android.databinding.tool.util.LoggedErrorException: Found data binding errors.
****/ data binding error ****msg:Cannot find the setter for attribute 'algolia:attribute' with parameter type java.lang.String on android.widget.TextView. file:/.../search/build/intermediates/packaged_res/debug/layout/search_result_item.xml loc:12:33 - 12:39 ****\ data binding error ****
`

**To Reproduce 🔍**
I followed the doc example precisely in my project. I made another project in order to try to replicate bug with less code but am unable to cause this bug in a bare bones project. I tried deleting all build folders, build caches and .idea folders. How can I debug this?

**Environment:**
 - OS: Android API 28
 - Android Studio 3.4
- Gradle 5.1.1 build tools 3.4.0

```

    implementation 'com.algolia:algoliasearch-android:3.27.0'
    implementation 'com.algolia:instantsearch-androidx:1.15.2'
    implementation 'com.algolia:instantsearch-androidx-core:1.15.2'

```
**Additional context**

```
<layout xmlns:algolia="http://schemas.android.com/apk/res-auto">
    <LinearLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:orientation="horizontal"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <TextView
            android:id="@+id/store_title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            algolia:attribute='@{"title"}'/>

   </LinearLayout>
</layout>
```

**Comment by samtipton** [comment]
So the cause seems to be that my DataBinderMapperImpl.java generated class is trying to import the SearchResultItemBindingImpl class from a location it is not in.

It's trying to import from

com.a.b.databinding.SearchResultItemBindingImpl

when the true location of the class is

com.a.search.databinding.SearchResultItemBindingImpl

**Comment by samtipton** [comment]
adding `kapt 'androidx.databinding:databinding-compiler:3.4.0'` fixed it. I didn't need to include this in my barebones project.

**Comment by PLNech** [comment]
Hi @samtipton, thanks for reporting this issue and sharing the workaround that fixed it. We will investigate to see if we can make it automatic, and else we'll add your solution to the README!
