### ISSUE TITLE
Allow SearchBox text size to be styleable

### ISSUE THREAD

**Issue by samtipton** [algolia/instantsearch-android#156]
**Is your feature request related to a problem? Please describe 🙏**
I can't change the font size of the SearchBox widget

**Describe the solution you'd like 🤔**
Expose a styleable attribute to change the text size of the query string and hint string

**Describe alternatives you've considered ✨**
Find underlying EditText by ID and change textSize at runtime

**Comment by PLNech** [comment]
Hi @samtipton, thanks for sharing this feature request!
The `SearchBox` is a subclass of `SearchView`, so it can be customized in the same way.

See our ecommerce app example, which displays a standard `SearchBox`:
![image](https://user-images.githubusercontent.com/1821404/59102561-bd5bff00-892c-11e9-8c60-b17336020d62.png)

Looking up how to set SearchView TextSize on the web, you'll find various methods: [this StackOverflow answer](https://stackoverflow.com/a/45829550/3109189) seems the best approach leveraging a Theme `Widget.AppCompat.SearchView` in `styles.xml`.

Here's how your `SearchBox` could look like following this advice:
![image](https://user-images.githubusercontent.com/1821404/59102629-ed0b0700-892c-11e9-9772-bf480329c6ec.png)

Let me know if you have further questions! Happy building :slightly_smiling_face:
