### ISSUE TITLE
Retrieving child view click event from OnItemClickListener

### ISSUE THREAD

**Issue by wonsuc** [algolia/instantsearch-android#157]
My RecyclerView's item view has many buttons, so I have to get each button's on click listener from my activity.

I tried to use this OOTB method.  

    mHits.setOnItemClickListener((recyclerView, position, v) -> {

    });

It works well, but this method only returns the item's container view, not children views. 

I can't figure out which child view is exactly clicked so I tried to find the way to implement by my self, but didn't succeed.

Is there any way to solve this? Thanks in advance.

**Comment by PLNech** [comment]
Hi @wonsuc, thanks for opening this issue!

Indeed, an `OnItemClickListener` will catch all clicks to the Hits' item, regardless of the area/button clicked. You should take a different approach if you want several clickable elements in your `hits_item.xml` layout:
    
- Adding the button with an `onClicked` method
  ```xml
  <!-- In your hits_item.xml layout -->
  <Button
      android:id="@+id/contactButton"
      android:onClick="contactClick"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content" />
   ```

- Implementing an `onClick` that fetches the hit and uses it
  
  ```java
  // In your Activity, add a method matching the button's onClick
  public void contactClick(View view) throws JSONException {
      Hits hits = findViewById(R.id.hits); // get a reference to your Hits
      View hitItem = (View) view.getParent(); // get the hit container from the clicked button
      int hitIndex = hits.indexOfChild(hitItem); // get the index of hit within Hits
      JSONObject hit = hits.get(hitIndex); // get the Json for this hit

      Toast.makeText(this, hit.optString("name"), Toast.LENGTH_LONG).show(); // use the hit however you want
  }
  ```

You should be able to use this method for several buttons, with an `onClick` method for each: the first lines will stay the same, the only difference being what you will do with the hit in each method.

Let me know how it goes, and please reopen the issue if that didn't solve your need!
