### ISSUE TITLE
AndroidX release lacks transitive dependencies

### ISSUE THREAD

**Issue by PLNech** [algolia/instantsearch-android#159]
It seems the latest `instantsearch-androidx` package doesn't ship with the following libraries:

- `com.algolia:instantsearch-androidx-core`
- `com.algolia:algoliasearch-android`
- `org.greenrobot:eventbus`
- `com.github.bumptech.glide:glide`
​

The issue was reported via HelpScout and on StackOverflow.

As a workaround, one should add some of the following lines to their application (depending on the features used, not all are required):
```groovy
    // InstantSearch
    implementation "com.algolia:instantsearch-androidx:$VERSION_INSTANTSEARCH"
    implementation "com.algolia:instantsearch-androidx-core:$VERSION_INSTANTSEARCH"
    implementation 'com.algolia:algoliasearch-android:3.27.0'
    implementation 'org.greenrobot:eventbus:3.1.1'
    implementation 'com.github.bumptech.glide:glide:4.7.1'
```

**Comment by Aallam** [comment]
This issue is related to the v1 of the library, which will be deprecated.
