### ISSUE TITLE
Androidx dependencies are not updated to latest release

### ISSUE THREAD

**Issue by danielgomezrico** [algolia/instantsearch-android#175]
In /releases there are multiple deploys on `2.0.x` version but that does not exist on maven repositories

https://mvnrepository.com/artifact/com.algolia/instantsearch-androidx

**Comment by q-litzler** [comment]
Hello,

You can use the artifact `com.algolia:instantsearch-android:2.0.2`, as all versions `2.0.x` include androidx.
