### ISSUE TITLE
Feature request: Connect Android AutoCompleteTextView to Instant Search SDK

### ISSUE THREAD

**Issue by user-fal** [algolia/instantsearch-android#185]
Hi team,

Great job for your android instant search SDK. I want to use it but wonder if it suits to my use case.
I have an android AutoCompleteTextView in a form and want to connect it to Algolia Search through your SDK. The form contains many fields to fill and one which will be able to user to make a search (by example type of something) and get the matched results within drop down list of AutocompleteTextView.

What widget is suitable for that or should I implement it myself? If so, what is the right steps to do it.

Thanks

**Comment by q-litzler** [comment]
Released in `2.2.0`.

You can have a look at this [example](https://github.com/algolia/instantsearch-android-examples/blob/master/showcase/src/main/kotlin/com/algolia/instantsearch/showcase/search/SearchAutoCompleteTextView.kt) to set it up.

Let us know if that works for you

**Comment by user-fal** [comment]
Hi @q-litzler,
I looked example.
Great, exactly what i need!  Thanks.
I'm wondering how to integrate filter on this. I have an index which contains mainly three fields: country, city and area. I have already made a search on area but want to make **a search on area depending country and city** selected in form. Could you show me the path?

**Comment by q-litzler** [comment]
Hello @user-fal 

If I understand you correctly, your user is typing into a autocomplete field, for example for a city name, and when selecting a result, it should add this city as a filter requirement of another search, is that correct ?

**Comment by user-fal** [comment]
@q-litzler not exactly what i want. It is only one search not "chained search".  The user types in autocomplete to search an area. But area is related to country and city. So i want that when user start typing i add these two filters for search. Hope it is more clear.

**Comment by Aallam** [comment]
Going through a cleanup process of all issues, we’re closing this issue, please feel free to reopen if the issue still affects you!
