### ISSUE TITLE
How do I invalidate DataSource when trigger SwipeRefreshLayout onRefresh?

### ISSUE THREAD

**Issue by b95505017** [algolia/instantsearch-android#195]
`LoadingConnectionSearcher` only call `searcher.searchAsync()` when `evenReload`, while `SearchBoxConnectionSearcherPagedList` will invalidate `DataSource` when `searchAsXX` triggered. Is it possible combine them together?

**Comment by Aallam** [comment]
Hello @b95505017,

If I get it right, you are asking for invalidating a `DataSource` on `eventReload` of `LoadingConnectionSearcher` ?

Actually, `LoadingConnectionSearcher` has no reference to any `DataSource`, therefore, no `DataSource` invalidation is done.  but we can do the following workaround to make it work:

```kotlin
val loading = LoadingConnector(searcher)
val liveData = LivePagedListBuilder(dataSourceFactory, pagedListConfig).build()

loading.viewModel.eventReload.subscribe {
  liveData.value?.dataSource?.invalidate()
}
```
