### ISSUE TITLE
Documentation examples of DiffUtil.ItemCallback

### ISSUE THREAD

**Issue by vn01971** [algolia/instantsearch-android#208]
In the [Getting Started Guide](https://www.algolia.com/doc/guides/building-search-ui/getting-started/android/), why does `areItemsTheSame` compare the classes of the items? Won't this always return true?
```kotlin
companion object : DiffUtil.ItemCallback<Product>() {

    override fun areItemsTheSame(
        oldItem: Product,
        newItem: Product
    ): Boolean {
        return oldItem::class == newItem::class // Why?
    }

    override fun areContentsTheSame(
        oldItem: Product,
        newItem: Product
    ): Boolean {
        return oldItem.name == newItem.name
    }
}
```

There's [an example](https://github.com/algolia/instantsearch-android/blob/develop/helper/src/androidTest/kotlin/documentation/widget/DocHitsPagingSingle.kt#L93) in this repo where `areItemsTheSame` checks the items' equality, which seems more correct:
```kotlin
companion object : DiffUtil.ItemCallback<Movie>() {

    override fun areItemsTheSame(
        oldItem: Movie,
        newItem: Movie
    ): Boolean {
        return oldItem == newItem
    }

    override fun areContentsTheSame(
        oldItem: Movie,
        newItem: Movie
    ): Boolean {
        return oldItem.title == newItem.title
    }
}
```

However, I still think that the implementations of `areItemsTheSame` and `areContentsTheSame` in the latter example aren't optimal. My understanding of [DiffUtil.Callback](https://developer.android.com/reference/androidx/recyclerview/widget/DiffUtil.Callback#public-methods_1) is that `areItemsTheSame` should compare the identifiers of the items and `areContentsTheSame` should compare all the items' data. It makes no difference for this specific example, but it would if more properties were added to `Movie`.
```kotlin
companion object : DiffUtil.ItemCallback<Movie>() {

    override fun areItemsTheSame(
        oldItem: Movie,
        newItem: Movie
    ): Boolean {
        return oldItem.title == newItem.title // assuming title uniquely identifies a Movie
    }

    override fun areContentsTheSame(
        oldItem: Movie,
        newItem: Movie
    ): Boolean {
        return oldItem == newItem
    }
}
```

**Comment by Aallam** [comment]
Hello @vn01971, thank you for your feedback! You are absolutely right, we will look into updating the snippets.
