### ISSUE TITLE
Issue with handling empty query

### ISSUE THREAD

**Issue by Isaackingston** [algolia/instantsearch-android#220]
I have created a custom component which extends SearchBoxView as  mentioned in the documentation.
[https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-display/android/#]. I made necessary changes to use this custom SearchBoxView. After making this changes also I am still getting results at the start of the app. I am following the getting started guide to implement the instant search feature.
Edit : I am using LiveData<PagedList\<Movies\>> and this seems to be causing the issue as it initially loads the data and there is no flag to the disable the initial loading.

**Comment by Aallam** [comment]
Hello @Isaackingston,
Are you using PagedList too? and if you can, please share a code snippet for a better understanding of your issue.

**Comment by Isaackingston** [comment]
I am using this sample like in the sample  : https://github.com/algolia/instantsearch-android-examples/blob/master/guides/src/main/kotlin/com/algolia/instantsearch/guides/gettingstarted/ProductFragment.kt
But I cannot disable the search for empty query. I am trying to disable initial search that is happening as soon as I navigate to this fragment. I tried to to use SearchBoxNoEmptyQuery (https://www.algolia.com/doc/guides/building-search-ui/going-further/conditional-display/android/#) in place of SearchBoxViewAppCompat.

**Comment by Isaackingston** [comment]
Thanks for looking into it quickly! But I am looking for something like what we have in iOS SDK. Please refer the code below :

`self.searcher!.shouldTriggerSearchForQuery = {
      query in
      if (query.query?.count ?? 0 > 2){
        self.hitsTableViewController?.hideErrorView()
        self.hitsTableViewController?.shouldShowResult()
        return true
      }else {
        self.hitsTableViewController?.showErrorView(NSLocalizedString("Enter more than 2 characters to perform search", comment: ""))
        self.hitsTableViewController?.shouldRemoveResult()
        return false
      }
    }` 

I want to control the trigger of search where I can stop empty query from being executed and also limit the number of characters after which the search will be triggered. IMO I think it makes sense to start searching after 2 or 3 characters. Please do advise me if this can be achieved in the current release.

**Comment by Aallam** [comment]
Hello @Isaackingston,

There are two aspects to take care of in your use case. 
* The initial loading: this should be possible to enable/disable it for empty queries with the PR above.
* When to query: you can create your own `SearchBoxView` as you have done before, here is an example of a possible implementation to trigger search two letters:
```kotlin
public class SearchBoxNoEmptyOrSmallQuery(
    public val searchView: SearchView
) : SearchBoxView {

    override var onQueryChanged: Callback<String?>? = null
    override var onQuerySubmitted: Callback<String?>? = null

    override fun setText(text: String?, submitQuery: Boolean) {
        searchView.setQuery(text, submitQuery)
    }

    init {
        searchView.setOnQueryTextListener(object : SearchView.OnQueryTextListener {

            override fun onQueryTextSubmit(query: String?): Boolean {
                if (query?.isNotEmpty() == true && query.length > 2) {
                    onQuerySubmitted?.invoke(query)
                }
                searchView.clearFocus();
                return false
            }

            override fun onQueryTextChange(query: String?): Boolean {
                if (query?.isNotEmpty() == true && query.length > 2) {
                    onQuerySubmitted?.invoke(query)
                }
                return false
            }
        })
    }
}
```
I hope this helps :)

**Comment by Isaackingston** [comment]
Cool it works! Thanks for your response. Would love to see this change getting merged soon. Any tentative date for release?

**Comment by Aallam** [comment]
>  Any tentative date for release?

Yes, it's today! 🎉 
For your use case, your data source factory can be something like this:
```kotlin
 val dataSourceFactory = SearcherSingleIndexDataSource.Factory(
        searcher = searcher,
        triggerSearchForQuery = { query ->
            query.query?.length.let { it != null && it > 2 }
        }
    ) { hit ->
        Product(
            hit.json.getValue("name").jsonPrimitive.content,
            hit.json["_highlightResult"]?.jsonObject
        )
    }
```
You may not even need a custom `SearchBoxView` with this new change!
Please give it a try: [2.7.3](https://github.com/algolia/instantsearch-android/releases/tag/2.7.3)

**Comment by Isaackingston** [comment]
That's awesome @Aallam . That was so quick. Thanks  🎉

**Comment by neenu89** [comment]
Hi @Aallam I tried both the custom SearchBoxView approach and triggerSearchForQuery. Both didn't work for me. I am using the version 2.10.0.
