### ISSUE TITLE
Landing page - Small glitch on conclusion CTA

### ISSUE THREAD

**Issue by sebnvzt** [algolia/instantsearch-android#24]
In the end of the mobile version of Android IS LP, the conclusion CTA is cut. 

Bug seen on iPhone 7+, with Safari.

![image uploaded from ios 1](https://cloud.githubusercontent.com/assets/23098634/24397576/f270130a-13a6-11e7-9826-4d6a5527a86b.jpg)

**Comment by LukyVj** [comment]
Need more input, cannot reproduce

**Comment by LukyVj** [comment]
Ok, there is definitely a problem on mobile resizing

**Comment by LukyVj** [comment]
The fix is in his way

**Comment by PLNech** [comment]
@sebnvzt I cannot reproduce the issue, is it still happening for you? And if yes, what screen size?

@LukyVj did you push the fix? If yes I'll close this issue 🙂
