### ISSUE TITLE
SearchboxView OnQueryChanged 

### ISSUE THREAD

**Issue by AdnanYupi** [algolia/instantsearch-android#249]
I wanna show custom progress bar inside the `SearchView` while user is typing. So idea was to observe `onQueryChanged` but I'm facing with the issue that ` searchBoxView.onQueryChanged = { p1 -> }` not being called if it is declared before adding to `connection += viewModel.searchBox.connectView(searchBoxView)`. But if it is added after, then it is being called but then search doesn't work. It doesn't retrieve any data when filtering in `SearchView`

Maybe I'm just doing something wrong but couldn't find any relevant topics on the internet. 

Thanks in advance

**Comment by Aallam** [comment]
Hi @AdnanYupi, connecting `SearchBoxView` [sets](https://github.com/algolia/instantsearch-android/blob/94093d357a400020afa7990e218f222ab84b76b8/instantsearch-core/src/commonMain/kotlin/com/algolia/instantsearch/core/searchbox/internal/SearchBoxConnectionView.kt#L15 ) `onQueryChanged`, which may override any previous callbacks; this is a common pattern in many android components.

As a workaround, you can implement `SearchBoxView` and use a [composite pattern](https://en.wikipedia.org/wiki/Composite_pattern) for your `onQueryChanged` like this: 

```kotlin
class CallbackComposite(
    private val callbacks: MutableList<Callback<String?>?> = mutableListOf()
) : Callback<String?> {

    operator fun add(callback: Callback<String?>?) {
        callbacks.add(callback)
    }

    override fun invoke(p1: String?) {
        callbacks.forEach {
            it?.invoke(p1)
        }
    }
}
```
Then use it like this:
```kotlin
class MySearchBoxView(val searchView: SearchView) : SearchBoxView {

    val onQueryChangedCallbacks = CallbackComposite()

    override var onQueryChanged: Callback<String?>?
        get() = onQueryChangedCallbacks
        set(value) {
            onQueryChangedCallbacks += value
        }
// ...
}
```
I hope this helps.
