### ISSUE TITLE
Paging broken in 2.11.0?

### ISSUE THREAD

**Issue by anderstechno** [algolia/instantsearch-android#259]
**Describe the bug 🐛**
In this list of 176 items, only 72 items are shown when using `com.algolia:instantsearch-android:2.11.0`
If I downgrade to 2.10.0 I see all items.
We see the same for all lists with more than 72 items in our app.

**Screenshots 🖥**
![image](https://user-images.githubusercontent.com/86744820/135455354-b987e93a-12c6-462e-b4ca-8775fa87cd4a.png)

**Environment:**
 - OS: Android
 - Library Version: 2.11.0

**Additional context**
We want to use 2.11.0 since it fixed a crash we were having, but this bug might be worse than that crash: 
https://github.com/algolia/instantsearch-android/pull/234

**Comment by anderstechno** [comment]
Thanks for fixing it so quickly @Aallam. Any idea when the fix will be released? Downgrading to 2.10.0 doesn't work for us because of a crash you fixed in 2.11.0 I think.

**Comment by Aallam** [comment]
@anderstechno [2.11.1](https://github.com/algolia/instantsearch-android/releases/tag/2.11.1) is released :)
