### ISSUE TITLE
Update Docsearch color

### ISSUE THREAD

**Issue by LukyVj** [algolia/instantsearch-android#26]
To match the android color 
![](https://puu.sh/v18N0/447c056318.png)

**Comment by Haroenv** [comment]
and logo

**Comment by LukyVj** [comment]
See next issue #27

**Comment by LukyVj** [comment]
![](https://puu.sh/v1dxx/5cbdfce62f.png)

**Comment by PLNech** [comment]
Fixed in c3b1de4.
