### ISSUE TITLE
.aar file missing from 2.11.2 in Maven

### ISSUE THREAD

**Issue by matthewbartos** [algolia/instantsearch-android#272]
**Describe the bug 🐛**
.aar file is missing in all Maven repos

**To Reproduce 🔍**
1. Go to https://repo1.maven.org/maven2/com/algolia/instantsearch-android/2.11.2/
2. Observe no .aar file

**Expected behavior 💭**
2.11.2 aar file exists :)

404 error for:
https://repo.maven.apache.org/maven2/com/algolia/instantsearch-android/2.11.2/instantsearch-android-2.11.2.aar

**Comment by Aallam** [comment]
Hi @matthewbartos -- thank your report! the release process indeed missed uploading this file. Release [`2.11.3`](https://repo1.maven.org/maven2/com/algolia/instantsearch-android/2.11.3/) should have the missing artifacts; please give it a try!

**Comment by matthewbartos** [comment]
That was super fast @Aallam, thanks a lot! `2.11.3` works fine :tada:
