### ISSUE TITLE
OnItemClickListener on HitsView

### ISSUE THREAD

**Issue by janakaj** [algolia/instantsearch-android#34]
How can I retrieve the `ObjectID` from the `Hits` widget in an` OnItemClickListener`?

**Comment by PLNech** [comment]
Hi @janakaj, thank you for asking!

Once you implemented an OnItemClickListener, its callback will be called with the clicked position in the list: `onItemClick(RecyclerView recyclerView, int position, View v)`.

You can then use `position` to get the corresponding record via `hits.get(position)`:

```
hits.setOnItemClickListener(new ItemClickSupport.OnItemClickListener() {
        @Override public void onItemClick(RecyclerView recyclerView, int position, View v) {
            Log.e("DEBUG", "Click at position " + position + ", hit:" + hits.get(position));
        }
});
```

You will get the whole record as a JSONObject with `hits.get(position)`, on which you can call `getString("objectID")` to get the record's objectID.
