### ISSUE TITLE
Proguard config

### ISSUE THREAD

**Issue by fobo66** [algolia/instantsearch-android#38]
After enabling the Proguard in my project, I see a lot of errors caused by your library. So, I think you should update your config according to this tips:

## Eventbus

In my project, I don't use Eventbus at all, but I should write it's Proguard rules. It's kinda strange.

Here are its rules:

```
-keepattributes *Annotation*
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }

# Only required if you use AsyncExecutor
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}
```

## Jsonpath

Reasons are the same, here is the config:

```
-dontwarn com.jayway.jsonpath.spi.json.GsonJsonProvider
-dontwarn com.jayway.jsonpath.spi.json.JacksonJsonNodeJsonProvider
-dontwarn com.jayway.jsonpath.spi.json.JacksonJsonProvider
-dontwarn com.jayway.jsonpath.spi.json.TapestryJsdonProvider
-dontwarn com.jayway.jsonpath.spi.json.JsonOrgJsonProvider
-dontwarn com.jayway.jsonpath.spi.json.TapestryJsonProvider
-dontwarn com.jayway.jsonpath.spi.mapper.GsonMappingProvider*
-dontwarn com.jayway.jsonpath.spi.mapper.JacksonMappingProvider
-dontwarn com.jayway.jsonpath.spi.mapper.JsonOrgMappingProvider

# Necessary for ignoring json-smart's logging dependencies
-dontwarn org.slf4j.*
```

I can submit PR with edited `proguard-rules.pro` file later, if you agree with this.

**Comment by PLNech** [comment]
Hi @fobo66, thank you for reporting this issue!
Indeed I forgot to propagate the necessary proguard rules. Your PR would be welcome :)

**Comment by fobo66** [comment]
@PLNech thanks for the reply!

In which branch should I send PR?

**Comment by PLNech** [comment]
@fobo66 please target `develop`!
