### ISSUE TITLE
Over-concatenated user agents

### ISSUE THREAD

**Issue by redox** [algolia/instantsearch-android#45]
I got user agents that look like `algolia_for_android_(3.10.1);_android_(4.4.4);_instant_search_android_(0.5.1);_instant_search_android_(0.5.1);_instant_search_android_(0.5.1);_instant_search_android_(0.5.1);_instant_search_android_(0......`.

Are we kind of appending it again and again?

**Comment by PLNech** [comment]
Hey @redox, thanks for the report!
We append it once when a Searcher is initialised:
```java
private Searcher(@NonNull final Index index) {
        this.index = index;
        this.client = index.getClient();
        query = new Query();
        client.addUserAgent(new Client.LibraryVersion("InstantSearch Android", String.valueOf(BuildConfig.VERSION_NAME)));
    }
```

Which should happen only once with a given index, but a user might have done it several times which would explain the overconcatenation. I'll update the `Client` to check for an existing user agent before appending!
