### ISSUE TITLE
 Cannot find the setter for attribute 'algolia:attribute' with parameter type java.lang.String on android.widget.TextView

### ISSUE THREAD

**Issue by fobo66** [algolia/instantsearch-android#47]
Hello!

After updating to Android Studio 3.0 and to Android Gradle Plugin 3.0, I've encountered the following compile time error: `Error:(48, 38) Cannot find the setter for attribute 'algolia:attribute' with parameter type java.lang.String on android.widget.TextView.`

Here is my layout where I'm using this attribute:

```xml
            <TextView
                android:id="@+id/book_name"
                android:layout_width="150dp"
                android:layout_height="wrap_content"
                android:fontFamily="sans-serif-condensed"
                android:padding="6dp"
                android:textAlignment="center"
                android:textAppearance="@style/TextAppearance.AppCompat.Caption"
                android:textSize="20sp"
                android:typeface="normal"
                android:scrollHorizontally="false"
                android:maxLines="5"
                algolia:attribute='@{"name"}'
                android:layout_marginStart="8dp"
                app:layout_constraintLeft_toRightOf="@+id/cover"
                android:layout_marginLeft="8dp"
                android:layout_marginEnd="16dp"
                app:layout_constraintRight_toRightOf="parent"
                android:layout_marginRight="16dp"
                android:layout_marginTop="16dp"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintBottom_toBottomOf="parent"
                android:layout_marginBottom="16dp"
                app:layout_constraintHorizontal_bias="1.0"
                app:layout_constraintVertical_bias="0.0" />
```

Error is raised on 0.8.0 version of instantsearch, as well as on 1.1.2.

Looks like it's a problem in `BindingHelper` class where you set `@BindingAdapter("attribute")`. As in [docs](https://developer.android.com/topic/libraries/data-binding/index.html#custom_setters), now you need to set `"bind:attribute"` instead of just `"attribute"`, i.e. you need to set XML namespace here, and `"bind"` namespace is for custom namespaces.

**Comment by PLNech** [comment]
Hi @fobo66, thank you for reporting this!

I can indeed reproduce your issue on our example apps when updating them to `com.android.tools.build:gradle:3.0.0`. The problem is not related to the lack of namespace in `BindingAdapter` annotations: [according to google-developers "anything in the application namespace doesn’t need any namespace in the parameter"](https://medium.com/google-developers/android-data-binding-custom-setters-55a25a7aea47), and indeed adding a namespace to the annotation parameters results as well in `Error:(22, 34) Cannot find the setter for attribute 'algolia:attribute' with parameter type java.lang.String on android.widget.ImageView.`

I'll keep investigating this issue and will let you know of my progress here.

**Comment by sasha00123** [comment]
I have the same problem.  Is there any solution?

**Comment by PLNech** [comment]
Hi @sasha00123, for now we didn't find the cause of this issue. The only workaround we currently know is downgrading the gradle plugin to `2.2.3`. I am investigating further and will keep you updated.

**Comment by sasha00123** [comment]
@PLNech , thanks a lot for your answer. I've already done it. But it's hard to work with old plugin. How long can it take for you to fix this bug?

**Comment by PLNech** [comment]
@sasha00123 @fobo66 We released [1.1.4](https://github.com/algolia/instantsearch-android/releases/tag/1.1.4) which fixes the issue. 🙂

**Comment by sasha00123** [comment]
Thank you😀 I'm glad to hear it.

**Comment by robertmogos** [comment]
Hi @sasha00123. Did you give it a try? Did it fix your problem ? Thanks

**Comment by fobo66** [comment]
@robertmogos I've tried new version already, problem is fixed, project is built successfully.

**Comment by robertmogos** [comment]
I am glad it worked @fobo66. BTW, I sent you an email at skiinale2011 at gmail dot com. Are you still using that email ?
