### ISSUE TITLE
Old glide library 3.8.0 -> 4.3.1

### ISSUE THREAD

**Issue by sasha00123** [algolia/instantsearch-android#49]
You're using glide 3.8.0, however glide 4.3.1 is available. It's not possible to import the newest version of the library(because of the error) for other needs. The only way is to use old vesion, sometimes it's very sad.

**Comment by PLNech** [comment]
Hi @sasha00123, thanks for reporting this! I'll address this at the soonest.

**Comment by PLNech** [comment]
Fixed and released in [1.2.1](https://github.com/algolia/instantsearch-android/releases/new).
