### ISSUE TITLE
Error using instantsearch-android-1.4.1

### ISSUE THREAD

**Issue by trogalko** [algolia/instantsearch-android#62]
Hi, 
I got this gradle build error log when using instantsearch-android-1.4.1
compile 'com.algolia:instantsearch-android:1.+' on build.gradle
compileSdkVersion 27
    buildToolsVersion '26.0.2'
    defaultConfig {
        applicationId "com.fireeats"
        minSdkVersion 16
        targetSdkVersion 27

But its build normally when I change to : compile 'com.algolia:instantsearch-android:1.4.0'        

14:58:56.549 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
14:58:56.549 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:58:56.549 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
14:58:56.549 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
14:58:56.549 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Could not resolve all files for configuration ':app:debugCompileClasspath'.
14:58:56.549 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Could not find instantsearch-android.jar (com.algolia:instantsearch-android:1.4.1).
14:58:56.549 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Searched in the following locations:
14:58:56.549 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       https://jcenter.bintray.com/com/algolia/instantsearch-android/1.4.1/instantsearch-android-1.4.1.jar

Thank You

**Comment by PLNech** [comment]
Hi @trogalko, thanks for reporting this!
It seems an issue in the release of `v1.4.1` caused the artifacts to be missing from the final package. 
We released [1.4.2](https://github.com/algolia/instantsearch-android/releases/tag/1.4.2) which resolves this (along with an unrelated bugfix). 

Updating to `1.4.2` should solve your problem, please reopen this issue if it is not the case!
