### ISSUE TITLE
Wrong facet value count returned

### ISSUE THREAD

**Issue by FrancoisObob** [algolia/instantsearch-android#65]
Hi,
we have the same issue for iOS : https://github.com/algolia/instantsearch-ios/issues/27
actually, in our product list, we have a "brand" facet so in the SearchResult we have a nice list of 100 brands (the most popular).
If we apply a facet refinement with one or more of those brands, the SearchResult returns the filtered products with the brands facet values and their counts.
But if we apply a facet refinement with one or more brands that was not initially in the list of 100 (we can search brands), the SearchResult returns for those brands facet values a count equal to 0.
Everything works fine in the Algolia Dashboard, but not with the iOS & Android SDK.
Maybe we did something wrong, or maybe it is a bug in the SDK.
Thank you for your reply,

**Comment by PLNech** [comment]
Hi @FrancoisObob, thanks for reporting this!

As it seems to be the same issue in both libraries, I'll let you reply directly to @spinach's [comment](https://github.com/algolia/instantsearch-ios/issues/27#issuecomment-369917609) and we'll investigate from there.

**Comment by PLNech** [comment]
@FrancoisObob: I'll follow @spinach's move and close this issue until we have more details. If you still face this issue, please reopen this ticket and answer his [followup questions](https://github.com/algolia/instantsearch-ios/issues/27#issuecomment-369917609) 🙂
