### ISSUE TITLE
Unregister Result and Error listeners

### ISSUE THREAD

**Issue by zmsansan** [algolia/instantsearch-android#66]
Hello! I'am need in unregister Result and Error listeners functions.
In my custom Searcher i'am do it
`public Searcher unregisterResultListener(@NonNull AlgoliaResultsListener resultListener) {
        if (resultListeners.contains(resultListener)) {
            resultListeners.remove(resultListener);
        }
        return this;
    }`

and

`public Searcher unregisterErrorListener(@NonNull AlgoliaErrorListener errorListener) {
        if (errorListeners.contains(errorListener)) {
            errorListeners.remove(errorListener);
        }
        return this;
    }`

Thanks!

**Comment by PLNech** [comment]
Hi @zmsansan, thanks for reporting this! That was already in the pipe, and is now released as v1.6.0.
