### ISSUE TITLE
Unregister SearchView from InstantSearch

### ISSUE THREAD

**Issue by zmsansan** [algolia/instantsearch-android#70]
Hello!

API have method registerSearchView(@NonNull final Activity activity, @NonNull final android.support.v7.widget.SearchView searchView) and similars at InstantSearch.

But, I need in method unregisterSearchView (for reuse SearchView with another a InstantSearch).

Please add, thanks!

**Comment by PLNech** [comment]
Hi @zmsansan, thanks for reporting this!

That's a good point, we'll implement the missing `unregisterSearchView`.

This being said, I'm curious: what's your use-case for using a `SearchView` with two different `InstantSearch`, but not using the two at the same time? 

As we decoupled the `SearchView` from `InstantSearch` because we had Multi-Index in mind (where you want a single SearchView to trigger search in several InstantSearches at once), knowing more your use case will help us move forward in the right direction 🙂

**Comment by zmsansan** [comment]
I'am has index where its records has "type" like state or city. User goal is find or select city.
By default i'am show filter result with record with type city in first Hits view.
if user use search then search result is state or city. 
if user click on state then i'am need save search result first Hits view and show second Hits view where SearchBox be reused for search only cities of selected state.
 If user dont select cities of state and click back button then show saved first Hitsview  with states and cities.

For implement it i'am want reuse SearchBox from first Hits view to second Hits view by unregister and register metods.

**Comment by PLNech** [comment]
Hi @zmsansan, thanks for these details!

If I understand well, you want to implement the following:
## First screen
>User can search for states or cities.
- If the user selects a city, goal achieved.
- If the user selects a state, you show a different search interface: 

## Second screen
> User can search for cities in the state selected before.
- If the user selects a city, goal achieved.
- If the user presses back, he's back to the search results on the first screen.

---

Based on this understanding, you should implement two separate search interfaces:

- A main search interface (let's call it `MainSearchActivity`, searching across all cities and states. User can use the searchbox to type city or state name. When selecting a city he's good, when selecting a state he gets to the second search interface:
- The second search interface (let's call it `CitySearchActivity`), is called from `MainSearchActivity` with the name of the selected state. This interface displays list of cities using `filters=["state:STATE_NAME"]` to only display the cities in the selected state. This interface uses _another_ set of widgets (at least SearchBox and Hits) to let the user type a city name.

With such a setup, if the user presses back he'll be back to the first search interface, where the results will still be there. This is the easiest way to achieve what you're looking for!

Let me know how it goes, and don't hesitate to reopen this ticket if that doesn't work 🙂

**Comment by PLNech** [comment]
(This being said, I'll implement `unregisterSearchView` as it might still be useful in other cases.)
