### ISSUE TITLE
Written query in one SearchBox is displayed in the other SearchBox

### ISSUE THREAD

**Issue by zmsansan** [algolia/instantsearch-android#71]
I think in SearchBox class incorrect condition and written query in one SearchBox is displayed in the other SearchBox.

If change use   condition "this.equals(event.origin)" instead  "!this.equals(event.origin)"  then query dont displayed in other SearchBox

**Comment by PLNech** [comment]
Hi there, thanks for your report!

This behavior is on purpose, so several `SearchViews` linked to the same search interface will display the same data. 
Our intention was to make sure your users always see the query that corresponds to the current results, so they don't wonder why they see results for `Foo` while a SearchView contains `bar`. 
Consequently if you have several SearchViews, as they could all contain input, we synchronise the inputs between SearchViews.

Can you explain what you are trying to build? I'd like to understand why you want two SearchViews linked to the same search interface but not displaying the same value.

**Comment by zmsansan** [comment]
See https://github.com/algolia/instantsearch-android/issues/70#issuecomment-376914973
If i'am  can't reuse SearchBox then i'am create two SearchBox and need has in differents SearchBox own query

**Comment by PLNech** [comment]
Thanks for [your comment](https://github.com/algolia/instantsearch-android/issues/70#issuecomment-376914973), I know understand your use case!

As per my reply in #70, the way to build what you want is by having two separate search interfaces, each having its own `SearchBox`/`Hits`/`InstantSearch`.

Using two `SearchView`s in the same interface, they are meant to stay in sync. This is why you're seeing the content of the first view in the second one : separating your two search interfaces is the way to go!
