### ISSUE TITLE
Add three strip menu button to show Navigation Drawer on SearchBox widget

### ISSUE THREAD

**Issue by trogalko** [algolia/instantsearch-android#82]
**Feature: What is your use case for such a feature?**
Could You add a menu like button (three strips icon) to searchbox widget that I could use to show navigationdrawer, just like the one used by android google play app? That would be great, to eliminate the toolbar and give more room tho show the search results.
Thank You.

**Comment by PLNech** [comment]
Hi @trogalko, thanks for your feature suggestion! (and apologies for the slow reply)

From what I understand, you want to integrate our `SearchBox` in your app in the app bar, along with the "three strip" button to open the NavigationDrawer and potentially other Menu Items. It could look like this with the `SearchBox` collapsed:  

![App bar](https://developer.android.com/images/training/appbar/appbar_sheets.png)
This is a pattern we have implemented, but not documented yet (I'll make sure we do it before closing the issue). 

This being said, it's quite simple to implement. Have a look at the [**Add the app bar** training](https://developer.android.com/training/appbar/) which shows the steps to adding such a menu to an app. 

You can also check our [Media app](https://github.com/algolia/instantsearch-android-examples/tree/master/media), which implements a SearchBox in a Menu (although without the Navigation drawer button).

Let me know if this helps or if you have other questions/feedback!

**Comment by trogalko** [comment]
Thank You for your response, and apologies for my much slower responese (due to Eid Holidays),

Yes its work, I just checked to algolia instantsearch media example.
Currently I work on my project based on algolia instantsearch ecommerce example.
Thank You so much.
