### ISSUE TITLE
Upgrade Glide 4.3.1 -> 4.7.1

### ISSUE THREAD

**Issue by sverrirs** [algolia/instantsearch-android#94]
Currently the [Hits.java](https://github.com/algolia/instantsearch-android/blob/master/instantsearch/src/main/java/com/algolia/instantsearch/ui/views/Hits.java) class depends on an old version of the Glide library. This is inhibiting developers to upgrade to the latest version of Glide.

There have been some breaking changes/new features in the Glide library and it would be nice to be able to use the latest.  Thanks :)

_Related issues #49_

**Comment by PLNech** [comment]
Hi @sverrirs, thanks for opening this issue! I'll do the needed changes and will update you here once released :upside_down_face:

**Comment by PLNech** [comment]
[v1.13.0](https://github.com/algolia/instantsearch-android/releases/tag/1.13.0) ships the update you requested. Apologies for the delay in notifying you here!

**Comment by sverrirs** [comment]
Thank you for addressing this and for letting me know :)
